"""empty message

Revision ID: 728e0c4aac75
Revises: 50e4cfd8ee42
Create Date: 2022-05-29 10:42:21.182986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728e0c4aac75'
down_revision = '50e4cfd8ee42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('names')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('names',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='names_pkey')
    )
    # ### end Alembic commands ###
