"""empty message

Revision ID: 8138e5b16b32
Revises: a3d02183a3b0
Create Date: 2022-05-29 12:22:23.947380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8138e5b16b32'
down_revision = 'a3d02183a3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability_list', sa.Column('startTime', sa.DateTime(), nullable=False))
    op.add_column('availability_list', sa.Column('endTime', sa.DateTime(), nullable=False))
    op.drop_column('availability_list', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability_list', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('availability_list', 'endTime')
    op.drop_column('availability_list', 'startTime')
    # ### end Alembic commands ###
